### PR TITLE
[#241] Profile setting fix

### LINKED ISSUE #241: Profile Banner issue
**Describe the bug**
ProfileBanner is null but it only set to check for undefined

**To Reproduce**
1. Create a new account
2. Go to user profile.

**Expected behavior**
user profile should show, but its white

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### LINKED ISSUE #242: Profile Picture Issue
**Describe the bug**
When the profile picture is updated it does not show on the frontend unless the page is refreshed

**To Reproduce**
1. Goto Settings
2. Goto edit avatar
3. Upload a profile picture
4. Refresh

**Expected behavior**
Profile picture should be updated immediately

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by KirstyGong**
# Description:
https://github.com/SE701Team2/Updog/issues/241 fix the bugs by updating new default banner and set the check for profile banner for null

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing document](../CONTRIBUTING.md)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My code follows the code style of this project
- [ ] My code has been commented
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by ejstuart — APPROVED** [review]
LGTM!

**Review by scorpionknifes — APPROVED** [review]

File: frontend/src/pages/profileSettings/ProfileSettingsView.jsx [hunk 1]
```diff
@@ -50,7 +50,7 @@ const ProfileSettingsView = ({
           className={classes.bannerImg}
           src={
             // eslint-disable-next-line no-nested-ternary
-            profileBanner !== undefined
+            profileBanner !== null
```
Comment (scorpionknifes) [inline frontend/src/pages/profileSettings/ProfileSettingsView.jsx]:
```suggestion
            profileBanner != null
```

**Review by scorpionknifes — CHANGES_REQUESTED** [review]

**Review by scorpionknifes — APPROVED** [review]

**Comment by ejstuart** [comment]
Hi sorry, didn't realise you closed #242 but it doesn't fix that issue
