### PR TITLE
[#249] Minor changes to fix for demo

### LINKED ISSUE #249: Fix minor issues for the demo
**Describe the bug**
There are a couple issues that are found during demo.

These need to be fixed.

add comments
add random share/likes
fix bad sytaxx calls

### PR DESCRIPTION
**Pull request by scorpionknifes**
# Description:
Changed some stuff for the demo
Fixed minor issues found in demo

fixes #249

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](../CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My code follows the code style of this project
- [ ] My code has been commented
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

### CODE REVIEW

File: frontend/src/components/posts/interactions/InteractionsView.jsx [hunk 1]
```diff
@@ -10,9 +10,17 @@ const InteractionsView = ({
   onShare,
   usersLiked,
   usersShared,
+  hasShared,
+  hasLiked,
 }) => (
   <div className={classes.container}>
-    <div className={classes.like} onClick={onLike} data-testid="like-btn">
+    {console.log(hasLiked ? 'black' : 'grey')}
```
Comment (scorpionknifes) [inline frontend/src/components/posts/interactions/InteractionsView.jsx]:
```suggestion
```

**Review by ejstuart — APPROVED** [review]
LGTM!
